### ISSUE TITLE
Bug with sort on multiple keys?

### ISSUE THREAD

**Issue by charles-randall** [mayank-02/msort#2]
Using the attached 383 line file containing UUIDs, the output of msort doesn't match that of GNU sort or Busybox sort (which return the same result).

$ md5sum uuid.1234
27e48a1f7971314287a3d70c3a1f9923  uuid.1234

GNU sort,
$ LC_ALL=C sort -t- -k3,3 -k4,4 uuid.1234 | md5sum
3882c4e3465944a98eb35f7d0e9cea73  -

Busybox sort,
$ LC_ALL=C /tmp/sort -t- -k3,3 -k4,4 uuid.1234 | md5sum
3882c4e3465944a98eb35f7d0e9cea73  -

Msort,
$ LC_ALL=C /tmp/msort -t- -k3,3 -k4,4 uuid.1234 | md5sum
473e9fe8912e001ab79a2b41d3efca4f  -

[uuid.1234.txt](https://github.com/mayank-02/msort/files/6135943/uuid.1234.txt)

**Comment by mayank-02** [comment]
Yes, it's not exactly a bug. My current implementation _doesn't_ support multiple keys. It works fine with a single key if that suits your use case. I will add that to my README to avoid any confusion in future. Thanks.

Testing with single key:
GNU Sort
$ LC_ALL=C sort -t- -k3,3 uuid.1234.txt | md5sum 
572b8121199423f12a35e94d7d1193bb  -

Msort
$ LC_ALL=C msort -t- -k3,3 uuid.1234.txt | md5sum
572b8121199423f12a35e94d7d1193bb  -

**Comment by charles-randall** [comment]
If that's the case, then it should probably exit with a usage error if multiple keys are provided.
