### ISSUE TITLE
POSIX sort requires "-" command-line argument to be interpreted as "read from stdin"

### ISSUE THREAD

**Issue by charles-randall** [mayank-02/msort#4]
See the OPERANDS section of this document,

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sort.html

Msort,
$ echo "hello" | msort - 
Can't open file : No such file or directory

GNU sort,
$ echo "hello" | sort -
hello

**Comment by mayank-02** [comment]
Thanks for pointing it out. I've fixed this in https://github.com/mayank-02/msort/commit/344612b92523b173703374a772d3bef18bc7b9f9 . You can give it a look.

**Comment by charles-randall** [comment]
Confirmed fixed.
