### ISSUE TITLE
Magic 1024 arg to qsort()?

### ISSUE THREAD

**Issue by charles-randall** [mayank-02/msort#8]
Should this be STRSIZE or something else? A constant doesn't make sense.

$ grep qsort msort.c
 * Store sorted runs of the file made using in memory buffer and inbuilt qsort
            qsort(buffer, lines, 1024, numcompare);
            qsort(buffer, lines, 1024, strcompare);

**Comment by mayank-02** [comment]
You're right, it should be `STRSIZE`. Replaced it with it's macro. Pushed the change with https://github.com/mayank-02/msort/commit/faa842bd8623416cf332c702719e1a792863f4e3.
